# [alias]
# run-s3 = "run +esp --target xtensa-esp32s3-none-elf --features esp32s3 --no-default-features"
# run-c6 = "run +nightly --target riscv32imac-unknown-none-elf --features esp32c6 --no-default-features"

# [target.xtensa-esp32s3-none-elf]
# runner = "probe-rs run --chip=esp32s3 --preverify --always-print-stacktrace --no-location --catch-hardfault"
# # runner = "espflash flash --monitor --chip esp32s3 --log-format defmt --baud=921600"
# rustflags = [
#   "-C", "link-arg=-nostartfiles",
# ]

[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip=esp32c6 --preverify --always-print-stacktrace --no-location --catch-hardfault"
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  # "-C", "force-frame-pointers",
]

[env]
DEFMT_LOG="info"

[build]
rustflags = []

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
